import Header from '@/components/Header';
import './globals.css';
import Footer from '@/components/Footer';
import { Noto_Sans } from 'next/font/google';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const sans = Noto_Sans({ subsets: ['latin'], weight: '500' });

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={sans.className}>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
